:factory: $ yarn add -D eslint-plugin-node eslint-plugin-prettier
yarn add v1.22.5
warning package.json: "dependencies" has dependency "typescript" with range "^4.1.2" that collides with a dependency in "devDependencies" of the same name with version "^4.0.3"
warning package.json: "dependencies" has dependency "@types/node" with range "^12.0.0" that collides with a dependency in "devDependencies" of the same name with version "^14.11.2"
warning openseadragon-sandbox@0.1.0: "dependencies" has dependency "typescript" with range "^4.1.2" that collides with a dependency in "devDependencies" of the same name with version "^4.0.3"
warning openseadragon-sandbox@0.1.0: "dependencies" has dependency "@types/node" with range "^12.0.0" that collides with a dependency in "devDependencies" of the same name with version "^14.11.2"
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["eslint-plugin-prettier@^3.4.0"] is trying to unpack in the same destination "/Users/takeshi/Library/Caches/Yarn/v6/npm-eslint-plugin-prettier-3.4.0-cdbad3bf1dbd2b177e9825737fe63b476a08f0c7-integrity/node_modules/eslint-plugin-prettier" as pattern ["eslint-plugin-prettier@^3.1.4"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > eslint-plugin-node@11.1.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@3.0.1" has unmet peer dependency "eslint@>=4.19.1".
warning " > eslint-plugin-prettier@3.4.0" has unmet peer dependency "eslint@>=5.0.0".
warning " > eslint-plugin-prettier@3.4.0" has unmet peer dependency "prettier@>=1.13.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning openseadragon-sandbox@0.1.0: "dependencies" has dependency "typescript" with range "^4.1.2" that collides with a dependency in "devDependencies" of the same name with version "^4.0.3"
warning openseadragon-sandbox@0.1.0: "dependencies" has dependency "@types/node" with range "^12.0.0" that collides with a dependency in "devDependencies" of the same name with version "^14.11.2"
success Saved 2 new dependencies.
info Direct dependencies
├─ eslint-plugin-node@11.1.0
└─ eslint-plugin-prettier@3.4.0
info All dependencies
├─ eslint-plugin-node@11.1.0
└─ eslint-plugin-prettier@3.4.0
$ yarn run compile
yarn run v1.22.5
warning package.json: "dependencies" has dependency "@types/node" with range "^12.0.0" that collides with a dependency in "devDependencies" of the same name with version "^14.11.2"
warning package.json: "dependencies" has dependency "typescript" with range "^4.1.2" that collides with a dependency in "devDependencies" of the same name with version "^4.0.3"
$ tsc
node_modules/web-vitals/dist/modules/types.d.ts:6:15 - error TS2304: Cannot find name 'PerformanceEntry'.

6     entries: (PerformanceEntry | FirstInputPolyfillEntry | NavigationTimingPolyfillEntry)[];
                ~~~~~~~~~~~~~~~~

node_modules/web-vitals/dist/modules/types.d.ts:11:49 - error TS2304: Cannot find name 'PerformanceEntry'.

11 export interface PerformanceEventTiming extends PerformanceEntry {
                                                   ~~~~~~~~~~~~~~~~

node_modules/web-vitals/dist/modules/types.d.ts:12:22 - error TS2304: Cannot find name 'DOMHighResTimeStamp'.

12     processingStart: DOMHighResTimeStamp;
                        ~~~~~~~~~~~~~~~~~~~

node_modules/web-vitals/dist/modules/types.d.ts:13:20 - error TS2304: Cannot find name 'DOMHighResTimeStamp'.

13     processingEnd: DOMHighResTimeStamp;
                      ~~~~~~~~~~~~~~~~~~~

node_modules/web-vitals/dist/modules/types.d.ts:14:15 - error TS2304: Cannot find name 'DOMHighResTimeStamp'.

14     duration: DOMHighResTimeStamp;
                 ~~~~~~~~~~~~~~~~~~~

node_modules/web-vitals/dist/modules/types.d.ts:22:58 - error TS2304: Cannot find name 'PerformanceNavigationTiming'.

22 export declare type NavigationTimingPolyfillEntry = Omit<PerformanceNavigationTiming, 'initiatorType' | 'nextHopProtocol' | 'redirectCount' | 'transferSize' | 'encodedBodySize' | 'decodedBodySize' | 'toJSON'>;
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 6 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.